### ISSUE TITLE
password default minimum length in 2024

### ISSUE THREAD

**Issue by pumano** [dariowskii/password_strength_checker#6]
Min length in 8 characters is too weak, maybe change defaults to 12?

![2024-03-11 11 29 36](https://github.com/dariowskii/password_strength_checker/assets/17675259/447ed32b-fdeb-4d88-b02c-0b9e4e67007c)

**Comment by dariowskii** [comment]
Hi @pumano!

It might actually be a good idea 💡 
if you want to contribute, you can update the `PasswordStrength` value and update the tests!
